version: '3.4'
networks:
  dev:
    driver: bridge
services:
  employee-demo:
    image: docker.io/library/employeedemo
    depends_on:
     - "employee_db"
    container_name: employeedemo-service
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Username=postgres;Password=postgres;Server=employee_db;Port=5432;Database=postgres;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  employee_db:
    image: postgres:latest
    container_name: employee_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - employee_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  employee_data: